/*
 * le_disasm - Linear Executable disassembler
 */
/** @file known_labels_swars.cpp
 *     Setup for symbols specific to the known biary from Syndicate Wars.
 * @par Purpose:
 *     Creates labels which implrove dissassembled output for a specific
 *     known input file.
 * @author   Unavowed <unavowed@vexillium.org>
 * @date     2010-09-20 - 2024-01-10
 * @par  Copying and copyrights:
 *     This program is free software; you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation; either version 2 of the License, or
 *     (at your option) any later version.
 */
anal.set_label (Label (0x025990, Label::FUNCTION, "unused_func_074"));
anal.set_label (Label (0x0359c0, Label::FUNCTION));
anal.set_label (Label (0x03cf38, Label::FUNCTION));
anal.set_label (Label (0x03d174, Label::FUNCTION));
anal.set_label (Label (0x03d3b0, Label::FUNCTION));
anal.set_label (Label (0x0426fc, Label::FUNCTION, "draw_unkn_func_07"));
anal.set_label (Label (0x060090, Label::FUNCTION, "unused_func_130"));
anal.set_label (Label (0x08c578, Label::FUNCTION));
anal.set_label (Label (0x0b8860, Label::FUNCTION, "unused_func_200"));
anal.set_label (Label (0x0b8914, Label::FUNCTION, "unused_func_201"));
anal.set_label (Label (0x0b8acc, Label::FUNCTION, "unused_func_202"));
anal.set_label (Label (0x0b8c0c, Label::FUNCTION, "unused_func_203"));
anal.set_label (Label (0x0b8f48, Label::FUNCTION, "person_command_to_text"));
anal.set_label (Label (0x0ba010, Label::FUNCTION, "unused_func_204"));
anal.set_label (Label (0x0ba6e4, Label::FUNCTION, "unused_func_205"));
anal.set_label (Label (0x0bac50, Label::FUNCTION, "unused_func_022"));
anal.set_label (Label (0x0d265c, Label::FUNCTION));
anal.set_label (Label (0x0d299c, Label::FUNCTION));
anal.set_label (Label (0x08e2bc, Label::FUNCTION));
anal.set_label (Label (0x08e398, Label::FUNCTION));
anal.set_label (Label (0x08e32c, Label::FUNCTION));
anal.set_label (Label (0x0d2d3c, Label::FUNCTION));
anal.set_label (Label (0x0d2ea4, Label::FUNCTION));
anal.set_label (Label (0x0d56d0, Label::FUNCTION));
anal.set_label (Label (0x0d5784, Label::FUNCTION));
anal.set_label (Label (0x0d25ec, Label::FUNCTION));
anal.set_label (Label (0x0d4090, Label::FUNCTION));
anal.set_label (Label (0x0d4fdc, Label::FUNCTION));
anal.set_label (Label (0x0cffb8, Label::FUNCTION));
anal.set_label (Label (0x0d2f18, Label::FUNCTION));
anal.set_label (Label (0x0d2fe4, Label::FUNCTION));
anal.set_label (Label (0x0d3480, Label::FUNCTION));
anal.set_label (Label (0x0d29a4, Label::FUNCTION));
anal.set_label (Label (0x094f08, Label::FUNCTION));
anal.set_label (Label (0x09bbe4, Label::FUNCTION));
anal.set_label (Label (0x0d30a4, Label::FUNCTION));
anal.set_label (Label (0x094844, Label::FUNCTION));
anal.set_label (Label (0x08c84c, Label::FUNCTION));
anal.set_label (Label (0x093f30, Label::FUNCTION));
anal.set_label (Label (0x0917b8, Label::FUNCTION));
anal.set_label (Label (0x090d98, Label::FUNCTION));
anal.set_label (Label (0x099ac8, Label::FUNCTION));
anal.set_label (Label (0x095910, Label::FUNCTION));
anal.set_label (Label (0x0d2a84, Label::FUNCTION));
anal.set_label (Label (0x096f80, Label::FUNCTION));
anal.set_label (Label (0x097718, Label::FUNCTION));
anal.set_label (Label (0x0930dc, Label::FUNCTION));
anal.set_label (Label (0x0d57b8, Label::FUNCTION));
anal.set_label (Label (0x097d5c, Label::FUNCTION));
anal.set_label (Label (0x097654, Label::FUNCTION));
anal.set_label (Label (0x0924d0, Label::FUNCTION));
anal.set_label (Label (0x098f1c, Label::FUNCTION));
anal.set_label (Label (0x0901e0, Label::FUNCTION));
anal.set_label (Label (0x0906e4, Label::FUNCTION));
anal.set_label (Label (0x0d3184, Label::FUNCTION));
anal.set_label (Label (0x08fbd8, Label::FUNCTION));
anal.set_label (Label (0x08fed4, Label::FUNCTION));
anal.set_label (Label (0x098278, Label::FUNCTION));
anal.set_label (Label (0x08d4e0, Label::FUNCTION));
anal.set_label (Label (0x0d2e90, Label::FUNCTION));
anal.set_label (Label (0x0d33b8, Label::FUNCTION));
anal.set_label (Label (0x0d3128, Label::FUNCTION));
anal.set_label (Label (0x098b80, Label::FUNCTION));
anal.set_label (Label (0x0d3388, Label::FUNCTION));
anal.set_label (Label (0x0d38b0, Label::FUNCTION));
anal.set_label (Label (0x0d348c, Label::FUNCTION));
anal.set_label (Label (0x08eb50, Label::FUNCTION));
anal.set_label (Label (0x08e7ec, Label::FUNCTION));
anal.set_label (Label (0x0d36bc, Label::FUNCTION));
anal.set_label (Label (0x0d345c, Label::FUNCTION));
anal.set_label (Label (0x0d3274, Label::FUNCTION));
anal.set_label (Label (0x08e3c0, Label::FUNCTION));
anal.set_label (Label (0x0d3078, Label::FUNCTION));
anal.set_label (Label (0x0d3400, Label::FUNCTION));
anal.set_label (Label (0x0d3ff8, Label::FUNCTION));
anal.set_label (Label (0x0d3038, Label::FUNCTION));
anal.set_label (Label (0x0d33e8, Label::FUNCTION));
anal.set_label (Label (0x08ede0, Label::FUNCTION));
anal.set_label (Label (0x0d3e18, Label::FUNCTION));
anal.set_label (Label (0x0d3040, Label::FUNCTION));
anal.set_label (Label (0x0d3e0c, Label::FUNCTION));
anal.set_label (Label (0x0d3988, Label::FUNCTION));
anal.set_label (Label (0x0d396c, Label::FUNCTION));
anal.set_label (Label (0x08d0d8, Label::FUNCTION));
anal.set_label (Label (0x08d300, Label::FUNCTION));
anal.set_label (Label (0x0d3b5c, Label::FUNCTION));
anal.set_label (Label (0x0d39a4, Label::FUNCTION));
anal.set_label (Label (0x0d3b3c, Label::FUNCTION));
anal.set_label (Label (0x0ccee8, Label::FUNCTION));
anal.set_label (Label (0x0b3458, Label::FUNCTION));
anal.set_label (Label (0x0b3da4, Label::FUNCTION));
anal.set_label (Label (0x0b59ec, Label::FUNCTION));
anal.set_label (Label (0x0d30cc, Label::FUNCTION));
anal.set_label (Label (0x0b26cc, Label::FUNCTION));
anal.set_label (Label (0x0b6bec, Label::FUNCTION));
anal.set_label (Label (0x0b2780, Label::FUNCTION));
anal.set_label (Label (0x0d278c, Label::FUNCTION));
anal.set_label (Label (0x0d26d4, Label::FUNCTION));
anal.set_label (Label (0x0dceac, Label::FUNCTION));
anal.set_label (Label (0x010003, Label::FUNCTION));
/* 0x00e5af1 is data */
/* 0x00e73e2 is data */
anal.set_label (Label (0x0e9638, Label::FUNCTION));
anal.set_label (Label (0x0ebc50, Label::FUNCTION));
anal.set_label (Label (0x0ec4f4, Label::FUNCTION));
anal.set_label (Label (0x0ef000, Label::FUNCTION));
anal.set_label (Label (0x0f0340, Label::FUNCTION));
anal.set_label (Label (0x140000, Label::FUNCTION));
anal.set_label (Label (0x0fa8f6, Label::FUNCTION));
anal.set_label (Label (0x0fa9c7, Label::FUNCTION));
anal.set_label (Label (0x0f9d46, Label::FUNCTION));
anal.set_label (Label (0x0f9d7c, Label::FUNCTION));
anal.set_label (Label (0x0f9db2, Label::FUNCTION));
anal.set_label (Label (0x0f9de8, Label::FUNCTION));
anal.set_label (Label (0x0f9d31, Label::FUNCTION));
anal.set_label (Label (0x0f9ecf, Label::FUNCTION));
anal.set_label (Label (0x0fbf80, Label::FUNCTION));
anal.set_label (Label (0x0fbec0, Label::FUNCTION));
anal.set_label (Label (0x0fc1d0, Label::FUNCTION));
anal.set_label (Label (0x0fbf40, Label::FUNCTION));
anal.set_label (Label (0x0fbd90, Label::FUNCTION));
anal.set_label (Label (0x0fbe40, Label::FUNCTION));
anal.set_label (Label (0x0fbd50, Label::FUNCTION));
anal.set_label (Label (0x0fbce0, Label::FUNCTION));
anal.set_label (Label (0x0fbeb0, Label::FUNCTION));
anal.set_label (Label (0x1078f0, Label::FUNCTION));
anal.set_label (Label (0x101780, Label::FUNCTION));
anal.set_label (Label (0x109170, Label::FUNCTION));
anal.set_label (Label (0x1095a0, Label::FUNCTION));
anal.set_label (Label (0x10b32e, Label::FUNCTION));
anal.set_label (Label (0x11ae70, Label::FUNCTION));
anal.set_label (Label (0x118a80, Label::FUNCTION));
anal.set_label (Label (0x11aebc, Label::FUNCTION));
anal.set_label (Label (0x10f160, Label::FUNCTION));
anal.set_label (Label (0x10f1a0, Label::FUNCTION)); /* XXX: strange */
anal.set_label (Label (0x110e62, Label::FUNCTION));
anal.set_label (Label (0x1111cc, Label::FUNCTION));
anal.set_label (Label (0x112280, Label::FUNCTION));
anal.set_label (Label (0x1118d0, Label::FUNCTION));
anal.set_label (Label (0x113ec0, Label::FUNCTION));
anal.set_label (Label (0x112910, Label::FUNCTION));
anal.set_label (Label (0x113070, Label::FUNCTION));
anal.set_label (Label (0x114600, Label::FUNCTION));
anal.set_label (Label (0x113f80, Label::FUNCTION));
anal.set_label (Label (0x1142a0, Label::FUNCTION));
anal.set_label (Label (0x114390, Label::FUNCTION));
anal.set_label (Label (0x117720, Label::FUNCTION));
anal.set_label (Label (0x1156a0, Label::FUNCTION));
anal.set_label (Label (0x115e40, Label::FUNCTION));
anal.set_label (Label (0x118430, Label::FUNCTION));
anal.set_label (Label (0x117a30, Label::FUNCTION));
anal.set_label (Label (0x117e20, Label::FUNCTION));
anal.set_label (Label (0x117df0, Label::FUNCTION));
anal.set_label (Label (0x11f547, Label::FUNCTION));
anal.set_label (Label (0x1200b9, Label::FUNCTION));
anal.set_label (Label (0x120843, Label::FUNCTION));
anal.set_label (Label (0x1208b5, Label::FUNCTION, "__FPEHandler_"));
anal.set_label (Label (0x139c83, Label::FUNCTION));
anal.set_label (Label (0x13a493, Label::FUNCTION));
anal.set_label (Label (0x13a643, Label::FUNCTION));
anal.set_label (Label (0x13b713, Label::FUNCTION));
anal.set_label (Label (0x13bf23, Label::FUNCTION));
anal.set_label (Label (0x13c073, Label::FUNCTION));
anal.set_label (Label (0x13c203, Label::FUNCTION));
anal.set_label (Label (0x13c0e0, Label::JUMP));
anal.set_label (Label (0x13b3f0, Label::FUNCTION));
anal.set_label (Label (0x13b730, Label::FUNCTION));
anal.set_label (Label (0x13bf40, Label::FUNCTION));
anal.set_label (Label (0x13c090, Label::FUNCTION));
anal.set_label (Label (0x13a500, Label::JUMP));
anal.set_label (Label (0x139940, Label::FUNCTION));
anal.set_label (Label (0x139ca0, Label::FUNCTION));
anal.set_label (Label (0x13a4b0, Label::FUNCTION));
anal.set_label (Label (0x05dbe0, Label::FUNCTION));
anal.set_label (Label (0x05eff0, Label::FUNCTION, "thin_wall_at_line"));
anal.set_label (Label (0x05f0e0, Label::FUNCTION, "thin_wall_around_object"));
anal.set_label (Label (0x07e85c, Label::FUNCTION, "Synd_nav_rulesA2B"));
anal.set_label (Label (0x07e918, Label::FUNCTION, "triangulation_allocate"));
anal.set_label (Label (0x07eb98, Label::FUNCTION, "triangulation_init_edges"));
anal.set_label (Label (0x07ec24, Label::FUNCTION, "triangulation_initxy"));
anal.set_label (Label (0x07eda0, Label::FUNCTION, "triangulation_clear"));
anal.set_label (Label (0x07f5ac, Label::FUNCTION, "triangle_find8"));
anal.set_label (Label (0x081540, Label::FUNCTION, "delete_point"));
anal.set_label (Label (0x081964, Label::FUNCTION, "make_edge"));
anal.set_label (Label (0x0827a0, Label::FUNCTION, "tri_set_rectangle"));
anal.set_label (Label (0x086624, Label::FUNCTION, "delaunay_step"));
anal.set_label (Label (0x0867ac, Label::FUNCTION, "fringe_get_rectangle"));
anal.set_label (Label (0x0868c8, Label::FUNCTION, "triangulate_set_rectangle"));
anal.set_label (Label (0x0868e0, Label::FUNCTION, "triangulate_area"));
anal.set_label (Label (0x0869f8, Label::FUNCTION, "triangulate_map"));
anal.set_label (Label (0x0eea38, Label::FUNCTION));
anal.set_label (Label (0x10aea3, Label::FUNCTION));
anal.set_label (Label (0x10de8c, Label::FUNCTION));
anal.set_label (Label (0x10de90, Label::FUNCTION));
anal.set_label (Label (0x10de97, Label::FUNCTION));
anal.set_label (Label (0x10def4, Label::FUNCTION));
anal.set_label (Label (0x10def8, Label::FUNCTION));
anal.set_label (Label (0x10df05, Label::FUNCTION));
anal.set_label (Label (0x10f110, Label::FUNCTION));
anal.set_label (Label (0x13a660, Label::FUNCTION));
anal.set_label (Label (0x13a66c, Label::FUNCTION));
anal.set_label (Label (0x13a678, Label::FUNCTION));
anal.set_label (Label (0x13a684, Label::FUNCTION));
anal.set_label (Label (0x13a690, Label::FUNCTION));
anal.set_label (Label (0x13a6a0, Label::FUNCTION));
anal.set_label (Label (0x13a6b0, Label::FUNCTION));
anal.set_label (Label (0x13a6c0, Label::FUNCTION));
anal.set_label (Label (0x13a6d0, Label::FUNCTION));
anal.set_label (Label (0x13a6dc, Label::FUNCTION));
anal.set_label (Label (0x13a6e8, Label::FUNCTION));
anal.set_label (Label (0x13a6f4, Label::FUNCTION));
anal.set_label (Label (0x13a700, Label::FUNCTION));
anal.set_label (Label (0x13a710, Label::FUNCTION));
anal.set_label (Label (0x13a720, Label::FUNCTION));
anal.set_label (Label (0x13a730, Label::FUNCTION));
anal.set_label (Label (0x13a740, Label::FUNCTION));
anal.set_label (Label (0x13a74c, Label::FUNCTION));
anal.set_label (Label (0x13a758, Label::FUNCTION));
anal.set_label (Label (0x13a768, Label::FUNCTION));
anal.set_label (Label (0x13a774, Label::FUNCTION));
anal.set_label (Label (0x13a784, Label::FUNCTION));
anal.set_label (Label (0x13a794, Label::FUNCTION));
anal.set_label (Label (0x13a7a4, Label::FUNCTION));
anal.set_label (Label (0x13a7b4, Label::FUNCTION));
anal.set_label (Label (0x13a7c0, Label::FUNCTION));
anal.set_label (Label (0x13a7cc, Label::FUNCTION));
anal.set_label (Label (0x13a7d8, Label::FUNCTION));
anal.set_label (Label (0x13a7e4, Label::FUNCTION));
anal.set_label (Label (0x13a7f4, Label::FUNCTION));
anal.set_label (Label (0x13a804, Label::FUNCTION));
anal.set_label (Label (0x13a814, Label::FUNCTION));
anal.set_label (Label (0x13a824, Label::FUNCTION));
anal.set_label (Label (0x13a830, Label::FUNCTION));
anal.set_label (Label (0x13a840, Label::FUNCTION));
anal.set_label (Label (0x13a84c, Label::FUNCTION));
anal.set_label (Label (0x13a858, Label::FUNCTION));
anal.set_label (Label (0x13a868, Label::FUNCTION));
anal.set_label (Label (0x13a878, Label::FUNCTION));
anal.set_label (Label (0x13a888, Label::FUNCTION));
anal.set_label (Label (0x13a898, Label::FUNCTION));
anal.set_label (Label (0x13a8a4, Label::FUNCTION));
anal.set_label (Label (0x13a8b0, Label::FUNCTION));
anal.set_label (Label (0x13a8bc, Label::FUNCTION));
anal.set_label (Label (0x13a8c8, Label::FUNCTION));
anal.set_label (Label (0x13a8d8, Label::FUNCTION));
anal.set_label (Label (0x13a8e8, Label::FUNCTION));
anal.set_label (Label (0x13a8f8, Label::FUNCTION));
anal.set_label (Label (0x13a908, Label::FUNCTION));
anal.set_label (Label (0x13a914, Label::FUNCTION));
anal.set_label (Label (0x13a920, Label::FUNCTION));
anal.set_label (Label (0x13a92c, Label::FUNCTION));
anal.set_label (Label (0x13a938, Label::FUNCTION));
anal.set_label (Label (0x13a948, Label::FUNCTION));
anal.set_label (Label (0x13a958, Label::FUNCTION));
anal.set_label (Label (0x13a968, Label::FUNCTION));
anal.set_label (Label (0x13a978, Label::FUNCTION));
anal.set_label (Label (0x13a984, Label::FUNCTION));
anal.set_label (Label (0x13a990, Label::FUNCTION));
anal.set_label (Label (0x13a99c, Label::FUNCTION));
anal.set_label (Label (0x13a9a8, Label::FUNCTION));
anal.set_label (Label (0x13a9b8, Label::FUNCTION));
anal.set_label (Label (0x13a9c8, Label::FUNCTION));
anal.set_label (Label (0x13a9d8, Label::FUNCTION));
anal.set_label (Label (0x13a9e8, Label::FUNCTION));
anal.set_label (Label (0x13a9f8, Label::FUNCTION));
anal.set_label (Label (0x13aa08, Label::FUNCTION));
anal.set_label (Label (0x13aa18, Label::FUNCTION));
anal.set_label (Label (0x13aa28, Label::FUNCTION));
anal.set_label (Label (0x13aa34, Label::FUNCTION));
anal.set_label (Label (0x13aa40, Label::FUNCTION));
anal.set_label (Label (0x13aa50, Label::FUNCTION));
anal.set_label (Label (0x13aa5c, Label::FUNCTION));
anal.set_label (Label (0x13aa68, Label::FUNCTION));
anal.set_label (Label (0x13aa74, Label::FUNCTION));
anal.set_label (Label (0x13aa80, Label::FUNCTION));
anal.set_label (Label (0x13aa8c, Label::FUNCTION));
anal.set_label (Label (0x13aa9c, Label::FUNCTION));
anal.set_label (Label (0x13aaac, Label::FUNCTION));
anal.set_label (Label (0x13aabc, Label::FUNCTION));
anal.set_label (Label (0x13aacc, Label::FUNCTION));
anal.set_label (Label (0x13aadc, Label::FUNCTION));
anal.set_label (Label (0x13aaec, Label::FUNCTION));
anal.set_label (Label (0x13aafc, Label::FUNCTION));
anal.set_label (Label (0x13ab0c, Label::FUNCTION));
anal.set_label (Label (0x13ab18, Label::FUNCTION));
anal.set_label (Label (0x13ab20, Label::FUNCTION));
anal.set_label (Label (0x13ab2c, Label::FUNCTION));
anal.set_label (Label (0x13ab38, Label::FUNCTION));
anal.set_label (Label (0x13ab44, Label::FUNCTION));
anal.set_label (Label (0x13ab50, Label::FUNCTION));
anal.set_label (Label (0x13ab58, Label::FUNCTION));
anal.set_label (Label (0x13ab64, Label::FUNCTION));
anal.set_label (Label (0x13ab74, Label::FUNCTION));
anal.set_label (Label (0x13ab84, Label::FUNCTION));
anal.set_label (Label (0x13ab94, Label::FUNCTION));
anal.set_label (Label (0x13aba4, Label::FUNCTION));
anal.set_label (Label (0x13abb4, Label::FUNCTION));
anal.set_label (Label (0x13abc4, Label::FUNCTION));
anal.set_label (Label (0x13abd4, Label::FUNCTION));
anal.set_label (Label (0x13abe4, Label::FUNCTION));
anal.set_label (Label (0x13abf4, Label::FUNCTION));
anal.set_label (Label (0x13ac00, Label::FUNCTION));
anal.set_label (Label (0x13ac0c, Label::FUNCTION));
anal.set_label (Label (0x13ac1c, Label::FUNCTION));
anal.set_label (Label (0x13ac2c, Label::FUNCTION));
anal.set_label (Label (0x13ac38, Label::FUNCTION));
anal.set_label (Label (0x13ac44, Label::FUNCTION));
anal.set_label (Label (0x13ac54, Label::FUNCTION));
anal.set_label (Label (0x13ac64, Label::FUNCTION));
anal.set_label (Label (0x13ac74, Label::FUNCTION));
anal.set_label (Label (0x13ac84, Label::FUNCTION));
anal.set_label (Label (0x13ac94, Label::FUNCTION));
anal.set_label (Label (0x13aca4, Label::FUNCTION));
anal.set_label (Label (0x13acb4, Label::FUNCTION));
anal.set_label (Label (0x13acc4, Label::FUNCTION));
anal.set_label (Label (0x13acd4, Label::FUNCTION));
anal.set_label (Label (0x13ace0, Label::FUNCTION));
anal.set_label (Label (0x13acec, Label::FUNCTION));
anal.set_label (Label (0x13acfc, Label::FUNCTION));
anal.set_label (Label (0x13ad08, Label::FUNCTION));
anal.set_label (Label (0x13ad14, Label::FUNCTION));
anal.set_label (Label (0x13ad20, Label::FUNCTION));
anal.set_label (Label (0x13ad2c, Label::FUNCTION));
anal.set_label (Label (0x13ad38, Label::FUNCTION));
anal.set_label (Label (0x13ad48, Label::FUNCTION));
anal.set_label (Label (0x13ad58, Label::FUNCTION));
anal.set_label (Label (0x13ad68, Label::FUNCTION));
anal.set_label (Label (0x13ad78, Label::FUNCTION));
anal.set_label (Label (0x13ad84, Label::FUNCTION));
anal.set_label (Label (0x13ad90, Label::FUNCTION));
anal.set_label (Label (0x13ad9c, Label::FUNCTION));
anal.set_label (Label (0x13ada8, Label::FUNCTION));
anal.set_label (Label (0x13adb4, Label::FUNCTION));
anal.set_label (Label (0x13adc0, Label::FUNCTION));
anal.set_label (Label (0x13add0, Label::FUNCTION));
anal.set_label (Label (0x13addc, Label::FUNCTION));
anal.set_label (Label (0x13ade4, Label::FUNCTION));
anal.set_label (Label (0x13adf0, Label::FUNCTION));
anal.set_label (Label (0x13adf8, Label::FUNCTION));
anal.set_label (Label (0x13ae00, Label::FUNCTION));
anal.set_label (Label (0x13ae0c, Label::FUNCTION));
anal.set_label (Label (0x13ae18, Label::FUNCTION));
anal.set_label (Label (0x13ae24, Label::FUNCTION));
anal.set_label (Label (0x13ae30, Label::FUNCTION));
anal.set_label (Label (0x13ae3c, Label::FUNCTION));
anal.set_label (Label (0x13ae4c, Label::FUNCTION));
anal.set_label (Label (0x13ae58, Label::FUNCTION));
anal.set_label (Label (0x13ae64, Label::FUNCTION));
anal.set_label (Label (0x13ae74, Label::FUNCTION));
anal.set_label (Label (0x13ae80, Label::FUNCTION));
anal.set_label (Label (0x13ae8c, Label::FUNCTION));
anal.set_label (Label (0x13ae9c, Label::FUNCTION));
anal.set_label (Label (0x13aea8, Label::FUNCTION));
anal.set_label (Label (0x13aeb4, Label::FUNCTION));
anal.set_label (Label (0x13aec0, Label::FUNCTION));
anal.set_label (Label (0x13aecc, Label::FUNCTION));
anal.set_label (Label (0x13aed8, Label::FUNCTION));
anal.set_label (Label (0x13aee8, Label::FUNCTION));
anal.set_label (Label (0x13aef4, Label::FUNCTION));
anal.set_label (Label (0x13af00, Label::FUNCTION));
anal.set_label (Label (0x13af0c, Label::FUNCTION));
anal.set_label (Label (0x13af18, Label::FUNCTION));
anal.set_label (Label (0x13af24, Label::FUNCTION));
anal.set_label (Label (0x13af30, Label::FUNCTION));
anal.set_label (Label (0x13af3c, Label::FUNCTION));
anal.set_label (Label (0x13af44, Label::FUNCTION));
anal.set_label (Label (0x13af50, Label::FUNCTION));
anal.set_label (Label (0x13af5c, Label::FUNCTION));
anal.set_label (Label (0x13af64, Label::FUNCTION));
anal.set_label (Label (0x13af70, Label::FUNCTION));
anal.set_label (Label (0x13af78, Label::FUNCTION));
anal.set_label (Label (0x13af80, Label::FUNCTION));
anal.set_label (Label (0x13af8c, Label::FUNCTION));
anal.set_label (Label (0x13af98, Label::FUNCTION));
anal.set_label (Label (0x13afa4, Label::FUNCTION));
anal.set_label (Label (0x13afb0, Label::FUNCTION));
anal.set_label (Label (0x13afbc, Label::FUNCTION));
anal.set_label (Label (0x13afc8, Label::FUNCTION));
anal.set_label (Label (0x13afd4, Label::FUNCTION));
anal.set_label (Label (0x13afe0, Label::FUNCTION));
anal.set_label (Label (0x13afec, Label::FUNCTION));
anal.set_label (Label (0x13aff8, Label::FUNCTION));
anal.set_label (Label (0x13b008, Label::FUNCTION));
anal.set_label (Label (0x13b014, Label::FUNCTION));
anal.set_label (Label (0x13b01c, Label::FUNCTION));
anal.set_label (Label (0x13b028, Label::FUNCTION));
anal.set_label (Label (0x13b030, Label::FUNCTION));
anal.set_label (Label (0x13b038, Label::FUNCTION));
anal.set_label (Label (0x13b044, Label::FUNCTION));
anal.set_label (Label (0x13b050, Label::FUNCTION));
anal.set_label (Label (0x13b05c, Label::FUNCTION));
anal.set_label (Label (0x13b068, Label::FUNCTION));
anal.set_label (Label (0x13b078, Label::FUNCTION));
anal.set_label (Label (0x13b088, Label::FUNCTION));
anal.set_label (Label (0x13b098, Label::FUNCTION));
anal.set_label (Label (0x13b0a8, Label::FUNCTION));
anal.set_label (Label (0x13b0b8, Label::FUNCTION));
anal.set_label (Label (0x13b0c8, Label::FUNCTION));
anal.set_label (Label (0x13b0d8, Label::FUNCTION));
anal.set_label (Label (0x13b0e8, Label::FUNCTION));
anal.set_label (Label (0x13b0f4, Label::FUNCTION));
anal.set_label (Label (0x13b100, Label::FUNCTION));
anal.set_label (Label (0x13b10c, Label::FUNCTION));
anal.set_label (Label (0x13b118, Label::FUNCTION));
anal.set_label (Label (0x13b124, Label::FUNCTION));
anal.set_label (Label (0x13b130, Label::FUNCTION));
anal.set_label (Label (0x13b13c, Label::FUNCTION));
anal.set_label (Label (0x13b148, Label::FUNCTION));
anal.set_label (Label (0x13b158, Label::FUNCTION));
anal.set_label (Label (0x13b168, Label::FUNCTION));
anal.set_label (Label (0x13b178, Label::FUNCTION));
anal.set_label (Label (0x13b188, Label::FUNCTION));
anal.set_label (Label (0x13b198, Label::FUNCTION));
anal.set_label (Label (0x13b1a8, Label::FUNCTION));
anal.set_label (Label (0x13b1b8, Label::FUNCTION));
anal.set_label (Label (0x13b1c8, Label::FUNCTION));
anal.set_label (Label (0x13b1d4, Label::FUNCTION));
anal.set_label (Label (0x13b1e0, Label::FUNCTION));
anal.set_label (Label (0x13b1ec, Label::FUNCTION));
anal.set_label (Label (0x13b1f8, Label::FUNCTION));
anal.set_label (Label (0x13b204, Label::FUNCTION));
anal.set_label (Label (0x13b210, Label::FUNCTION));
anal.set_label (Label (0x13b220, Label::FUNCTION));
anal.set_label (Label (0x13b22c, Label::FUNCTION));
anal.set_label (Label (0x13b23c, Label::FUNCTION));
anal.set_label (Label (0x13b24c, Label::FUNCTION));
anal.set_label (Label (0x13b25c, Label::FUNCTION));
anal.set_label (Label (0x13b26c, Label::FUNCTION));
anal.set_label (Label (0x13b27c, Label::FUNCTION));
anal.set_label (Label (0x13b28c, Label::FUNCTION));
anal.set_label (Label (0x13b29c, Label::FUNCTION));
anal.set_label (Label (0x13b2ac, Label::FUNCTION));
anal.set_label (Label (0x13b2b8, Label::FUNCTION));
anal.set_label (Label (0x13b2c4, Label::FUNCTION));
anal.set_label (Label (0x13b2d0, Label::FUNCTION));
anal.set_label (Label (0x13b2dc, Label::FUNCTION));
anal.set_label (Label (0x13b2e8, Label::FUNCTION));
anal.set_label (Label (0x13b2f8, Label::FUNCTION));
anal.set_label (Label (0x13b304, Label::FUNCTION));
anal.set_label (Label (0x13b310, Label::FUNCTION));
anal.set_label (Label (0x13b320, Label::FUNCTION));
anal.set_label (Label (0x13b330, Label::FUNCTION));
anal.set_label (Label (0x13b340, Label::FUNCTION));
anal.set_label (Label (0x13b350, Label::FUNCTION));
anal.set_label (Label (0x13b360, Label::FUNCTION));
anal.set_label (Label (0x13b370, Label::FUNCTION));
anal.set_label (Label (0x13b380, Label::FUNCTION));
anal.set_label (Label (0x13b390, Label::FUNCTION));
anal.set_label (Label (0x13b39c, Label::FUNCTION));
anal.set_label (Label (0x13b3a8, Label::FUNCTION));
anal.set_label (Label (0x13b3b4, Label::FUNCTION));
anal.set_label (Label (0x13b3c0, Label::FUNCTION));
anal.set_label (Label (0x13b3cc, Label::FUNCTION));
anal.set_label (Label (0x13b3d8, Label::FUNCTION));
anal.set_label (Label (0x13b3e4, Label::FUNCTION));
anal.set_label (Label (0x120654, Label::FUNCTION));
anal.set_label (Label (0x120658, Label::FUNCTION));
anal.set_label (Label (0x120671, Label::FUNCTION));
anal.set_label (Label (0x10c989, Label::FUNCTION));
anal.set_label (Label (0x10c678, Label::FUNCTION));
anal.set_label (Label (0x10c650, Label::FUNCTION, "wcpp_error_undfcnstr"));
anal.set_label (Label (0x0c18c0, Label::FUNCTION, "__init_bin_obj_sizes"));
anal.set_label (Label (0x0f935c, Label::FUNCTION));
anal.set_label (Label (0x10b1d2, Label::FUNCTION, "store_STK"));
anal.set_label (Label (0x10de9c, Label::FUNCTION, "init_3"));
anal.set_label (Label (0x10df0a, Label::FUNCTION, "init_2"));
anal.set_label (Label (0x120159, Label::FUNCTION, "longjmpInit"));
anal.set_label (Label (0x120676, Label::FUNCTION, "init_1"));


anal.set_label (Label (0x010000, Label::FUNCTION, "__00012D030H"));
anal.set_label (Label (0x011b9c, Label::FUNCTION, "_main"));
anal.set_label (Label (0x012b60, Label::FUNCTION, "__nullsub_1"));
anal.set_label (Label (0x035644, Label::FUNCTION, "__nullsub_2"));
anal.set_label (Label (0x04a7f8, Label::FUNCTION, "__nullsub_3"));
anal.set_label (Label (0x06b138, Label::FUNCTION, "__nullsub_4"));
anal.set_label (Label (0x06f82c, Label::FUNCTION, "__nullsub_5"));
anal.set_label (Label (0x06f9dc, Label::FUNCTION, "__nullsub_6"));
anal.set_label (Label (0x06faa8, Label::FUNCTION, "__nullsub_7"));
anal.set_label (Label (0x0c19e8, Label::FUNCTION, "__nullsub_8"));
anal.set_label (Label (0x0c9050, Label::FUNCTION, "__nullsub_9"));
anal.set_label (Label (0x0e00a8, Label::FUNCTION, "__nullsub_10"));
anal.set_label (Label (0x0e0fd0, Label::FUNCTION, "_memset"));
anal.set_label (Label (0x0e0fe8, Label::FUNCTION, "__mem_putc_"));
anal.set_label (Label (0x0e0ffb, Label::FUNCTION, "_sprintf"));
anal.set_label (Label (0x0e49e7, Label::FUNCTION, "_atoi"));
anal.set_label (Label (0x0e581c, Label::FUNCTION, "__start"));
anal.set_label (Label (0x0e5aab, Label::FUNCTION, "____exit_"));
anal.set_label (Label (0x0e5aad, Label::FUNCTION, "____do_exit_with_msg__"));
anal.set_label (Label (0x0e5ae8, Label::FUNCTION, "____GETDS"));
anal.set_label (Label (0x0ea32a, Label::FUNCTION, "_time"));
anal.set_label (Label (0x0ea359, Label::FUNCTION, "_strrchr"));
anal.set_label (Label (0x0ea373, Label::FUNCTION, "_toupper"));
anal.set_label (Label (0x0ea390, Label::FUNCTION, "_strcmp"));
anal.set_label (Label (0x0ea431, Label::FUNCTION, "_tolower"));
anal.set_label (Label (0x0ee245, Label::FUNCTION, "____open_flags_"));
anal.set_label (Label (0x0ee316, Label::FUNCTION, "____doopen_"));
anal.set_label (Label (0x0ee3da, Label::FUNCTION, "___fsopen_"));
anal.set_label (Label (0x0ee413, Label::FUNCTION, "_fopen"));
anal.set_label (Label (0x0ee41d, Label::FUNCTION, "__close_file_"));
anal.set_label (Label (0x0ee485, Label::FUNCTION, "_freopen"));
anal.set_label (Label (0x0ee4c7, Label::FUNCTION, "_fputc"));
anal.set_label (Label (0x0ee56b, Label::FUNCTION, "_fclose"));
anal.set_label (Label (0x0ee598, Label::FUNCTION, "____shutdown_stream_"));
anal.set_label (Label (0x0ee5ad, Label::FUNCTION, "____hex_"));
anal.set_label (Label (0x0ee5b9, Label::FUNCTION, "____MkTmpFile_"));
anal.set_label (Label (0x0ee61e, Label::FUNCTION, "____doclose_"));
anal.set_label (Label (0x0ee830, Label::FUNCTION, "__j___clock_"));
anal.set_label (Label (0x0ee9e6, Label::FUNCTION, "_rand"));
anal.set_label (Label (0x0eea0a, Label::FUNCTION, "_srand"));
anal.set_label (Label (0x0eefca, Label::FUNCTION, "____null_int23_exit_"));
anal.set_label (Label (0x0eefcb, Label::FUNCTION, "_exit"));
anal.set_label (Label (0x0eefe3, Label::FUNCTION, "___exit_"));
anal.set_label (Label (0x0f065f, Label::FUNCTION, "___dos_getvect_"));
anal.set_label (Label (0x0f0691, Label::FUNCTION, "___dos_setvect_"));
anal.set_label (Label (0x0f06be, Label::FUNCTION, "__cget_string_"));
anal.set_label (Label (0x0f06e7, Label::FUNCTION, "__uncget_string_"));
anal.set_label (Label (0x0f06eb, Label::FUNCTION, "_vsscanf"));
anal.set_label (Label (0x0f0712, Label::FUNCTION, "_sscanf"));
anal.set_label (Label (0x0f07e6, Label::FUNCTION, "_memmove"));
anal.set_label (Label (0x0f0b38, Label::FUNCTION, "__int386_"));
anal.set_label (Label (0x0f0b55, Label::FUNCTION, "___nfree_"));
anal.set_label (Label (0x0f0bd7, Label::FUNCTION, "___nmalloc_"));
anal.set_label (Label (0x0f0cba, Label::FUNCTION, "___nexpand_"));
anal.set_label (Label (0x0f0cf2, Label::FUNCTION, "____HeapManager_expand_"));
anal.set_label (Label (0x0f0eea, Label::FUNCTION, "_byteswap"));
anal.set_label (Label (0x0f0f10, Label::FUNCTION, "__med3_"));
anal.set_label (Label (0x0f0f68, Label::FUNCTION, "_qsort"));
anal.set_label (Label (0x0f13a1, Label::FUNCTION, "_strncmp"));
anal.set_label (Label (0x0f13ca, Label::FUNCTION, "_creat"));
anal.set_label (Label (0x0f13d7, Label::FUNCTION, "_setmode"));
anal.set_label (Label (0x0f1483, Label::FUNCTION, "_close"));
anal.set_label (Label (0x0f14a3, Label::FUNCTION, "_open"));
anal.set_label (Label (0x0f14c7, Label::FUNCTION, "_sopen"));
anal.set_label (Label (0x0f16b0, Label::FUNCTION, "____set_binary_"));
anal.set_label (Label (0x0f19f0, Label::FUNCTION, "____STOSB"));
anal.set_label (Label (0x0f1a27, Label::FUNCTION, "____STOSD"));
anal.set_label (Label (0x0f1a93, Label::FUNCTION, "____prtf_"));
anal.set_label (Label (0x0f1e32, Label::FUNCTION, "_getprintspecs"));
anal.set_label (Label (0x0f1f70, Label::FUNCTION, "_evalflags"));
anal.set_label (Label (0x0f1fcf, Label::FUNCTION, "__far_strlen_"));
anal.set_label (Label (0x0f1ff3, Label::FUNCTION, "__far_other_strlen_"));
anal.set_label (Label (0x0f2016, Label::FUNCTION, "__fmt4hex_"));
anal.set_label (Label (0x0f2074, Label::FUNCTION, "__FixedPoint_Format_"));
anal.set_label (Label (0x0f2169, Label::FUNCTION, "__float_format_"));
anal.set_label (Label (0x0f2170, Label::FUNCTION, "_formstring"));
anal.set_label (Label (0x0f2659, Label::FUNCTION, "_zupstr"));
anal.set_label (Label (0x0f29d6, Label::FUNCTION, "___searchenv_"));
anal.set_label (Label (0x0f2aca, Label::FUNCTION, "____update_buffer_"));
anal.set_label (Label (0x0f2b0c, Label::FUNCTION, "_fseek"));
anal.set_label (Label (0x0f2c08, Label::FUNCTION, "_ftell"));
anal.set_label (Label (0x0f2c4a, Label::FUNCTION, "_fread"));
anal.set_label (Label (0x0f3904, Label::FUNCTION, "_segread"));
anal.set_label (Label (0x0f392c, Label::FUNCTION, "__int386x_"));
anal.set_label (Label (0x0fab15, Label::FUNCTION, "____CMain"));
anal.set_label (Label (0x0fab64, Label::FUNCTION, "____InitRtns"));
anal.set_label (Label (0x0fabaf, Label::FUNCTION, "____FiniRtns"));
anal.set_label (Label (0x0fabfe, Label::FUNCTION, "__nullsub_14"));
anal.set_label (Label (0x0fabff, Label::FUNCTION, "____Init_Argv_"));
anal.set_label (Label (0x0facc0, Label::FUNCTION, "___SplitParms_"));
anal.set_label (Label (0x0faf94, Label::FUNCTION, "_access"));
anal.set_label (Label (0x0fafcf, Label::FUNCTION, "_tell"));
anal.set_label (Label (0x0fafe0, Label::FUNCTION, "_lseek"));
anal.set_label (Label (0x0fb023, Label::FUNCTION, "_read"));
anal.set_label (Label (0x0fb11e, Label::FUNCTION, "_write"));
anal.set_label (Label (0x0fb2f3, Label::FUNCTION, "_filelength"));
anal.set_label (Label (0x0fb330, Label::FUNCTION, "___dos_findfirst_"));
anal.set_label (Label (0x0fb34d, Label::FUNCTION, "___dos_findnext_"));
anal.set_label (Label (0x0fb369, Label::FUNCTION, "___dos_findclose_"));
anal.set_label (Label (0x0fb3b2, Label::FUNCTION, "_rename"));
anal.set_label (Label (0x0fb3e0, Label::FUNCTION, "__j_unlink_"));
anal.set_label (Label (0x0fb3e5, Label::FUNCTION, "____getctime_"));
anal.set_label (Label (0x0fb4a8, Label::FUNCTION, "_mktime"));
anal.set_label (Label (0x0ff369, Label::FUNCTION, "_getenv"));
anal.set_label (Label (0x108de7, Label::FUNCTION, "____set_EDOM_"));
anal.set_label (Label (0x108dec, Label::FUNCTION, "____set_errno_"));
anal.set_label (Label (0x108df8, Label::FUNCTION, "____set_ERANGE_"));
anal.set_label (Label (0x108dff, Label::FUNCTION, "____set_EINVAL_"));
anal.set_label (Label (0x108e0f, Label::FUNCTION, "____set_doserrno_"));
anal.set_label (Label (0x108e1b, Label::FUNCTION, "____allocfp_"));
anal.set_label (Label (0x108ec1, Label::FUNCTION, "____freefp_"));
anal.set_label (Label (0x108efa, Label::FUNCTION, "____purgefp_"));
anal.set_label (Label (0x108f18, Label::FUNCTION, "____chktty_"));
anal.set_label (Label (0x108f4a, Label::FUNCTION, "____ioalloc_"));
anal.set_label (Label (0x108fc1, Label::FUNCTION, "____flush_"));
anal.set_label (Label (0x1090a0, Label::FUNCTION, "____close_"));
anal.set_label (Label (0x1090d5, Label::FUNCTION, "__clock_value_"));
anal.set_label (Label (0x109130, Label::FUNCTION, "____clock_init_"));
anal.set_label (Label (0x10913b, Label::FUNCTION, "____clock_"));
anal.set_label (Label (0x109869, Label::FUNCTION, "_printf"));
anal.set_label (Label (0x10988b, Label::FUNCTION, "_gets"));
anal.set_label (Label (0x10a566, Label::FUNCTION, "___dos_getdate_"));
anal.set_label (Label (0x10a581, Label::FUNCTION, "___dos_gettime_"));
anal.set_label (Label (0x10a59c, Label::FUNCTION, "____MemAllocator"));
anal.set_label (Label (0x10a644, Label::FUNCTION, "____MemFree"));
anal.set_label (Label (0x10a74f, Label::FUNCTION, "____unlink_"));
anal.set_label (Label (0x10a7a0, Label::FUNCTION, "____FreeDPMIBlocks_"));
anal.set_label (Label (0x10a7fc, Label::FUNCTION, "____ReAllocDPMIBlock_"));
anal.set_label (Label (0x10a8fb, Label::FUNCTION, "____LinkUpNewMHeap_"));
anal.set_label (Label (0x10a96f, Label::FUNCTION, "____LastFree_"));
anal.set_label (Label (0x10a9bf, Label::FUNCTION, "__RationalAlloc_"));
anal.set_label (Label (0x10aa90, Label::FUNCTION, "____CreateNewNHeap_"));
anal.set_label (Label (0x10ab40, Label::FUNCTION, "____ExpandDGROUP_"));
anal.set_label (Label (0x10ac8c, Label::FUNCTION, "____AdjustAmount_"));
anal.set_label (Label (0x10ad0c, Label::FUNCTION, "____IOMode_"));
anal.set_label (Label (0x10ad61, Label::FUNCTION, "____SetIOMode_"));
anal.set_label (Label (0x10ad76, Label::FUNCTION, "_isatty"));
anal.set_label (Label (0x10ad9d, Label::FUNCTION, "___dosret0_"));
anal.set_label (Label (0x10ada4, Label::FUNCTION, "___dosretax_"));
anal.set_label (Label (0x10ada8, Label::FUNCTION, "____set_errno_dos_"));
anal.set_label (Label (0x10ae3e, Label::FUNCTION, "_utoa"));
anal.set_label (Label (0x10ae88, Label::FUNCTION, "_itoa"));
anal.set_label (Label (0x10aeda, Label::FUNCTION, "_ultoa"));
anal.set_label (Label (0x10af24, Label::FUNCTION, "_ltoa"));
anal.set_label (Label (0x10af4b, Label::FUNCTION, "_getcwd"));
anal.set_label (Label (0x10afd3, Label::FUNCTION, "_strlen"));
anal.set_label (Label (0x10afec, Label::FUNCTION, "_strcpy"));
anal.set_label (Label (0x10b00b, Label::FUNCTION, "_strcat"));
anal.set_label (Label (0x10b03e, Label::FUNCTION, "_fflush"));
anal.set_label (Label (0x10b04e, Label::FUNCTION, "____qread_"));
anal.set_label (Label (0x10b06d, Label::FUNCTION, "_fgetc"));
anal.set_label (Label (0x10b0f6, Label::FUNCTION, "____filbuf_"));
anal.set_label (Label (0x10b125, Label::FUNCTION, "____fill_buffer_"));
anal.set_label (Label (0x10b1da, Label::FUNCTION, "____CHK"));
anal.set_label (Label (0x10b1ea, Label::FUNCTION, "____GRO"));
anal.set_label (Label (0x10b1ed, Label::FUNCTION, "____STK"));
anal.set_label (Label (0x10b20b, Label::FUNCTION, "____STKOVERFLOW_"));
anal.set_label (Label (0x10b21a, Label::FUNCTION, "_fprintf"));
anal.set_label (Label (0x10b23b, Label::FUNCTION, "_putch"));
anal.set_label (Label (0x10b24a, Label::FUNCTION, "__j___delay_"));
anal.set_label (Label (0x10b250, Label::FUNCTION, "____int386x_"));
anal.set_label (Label (0x10b2ad, Label::FUNCTION, "___DoINTR_"));
anal.set_label (Label (0x10b801, Label::FUNCTION, "_stricmp"));
anal.set_label (Label (0x10b848, Label::FUNCTION, "_strnicmp"));
anal.set_label (Label (0x10de30, Label::FUNCTION, "____wcpp_2_module_dtor__"));
anal.set_label (Label (0x10dea7, Label::FUNCTION, "____wcpp_2_mod_register__"));
anal.set_label (Label (0x10deb7, Label::FUNCTION, "_memcpy"));
anal.set_label (Label (0x10dedc, Label::FUNCTION, "_outp"));
anal.set_label (Label (0x10dee6, Label::FUNCTION, "_inp"));
anal.set_label (Label (0x10df15, Label::FUNCTION, "____wcpp_2_fun_register__"));
anal.set_label (Label (0x10df28, Label::FUNCTION, "____CommonInit_"));
anal.set_label (Label (0x10df92, Label::FUNCTION, "____doserror_"));
anal.set_label (Label (0x10dfa5, Label::FUNCTION, "_unlink"));
anal.set_label (Label (0x10dfc6, Label::FUNCTION, "____leapyear_"));
anal.set_label (Label (0x10e001, Label::FUNCTION, "__calc_yday_"));
anal.set_label (Label (0x10e0e6, Label::FUNCTION, "__check_order_"));
anal.set_label (Label (0x10e11a, Label::FUNCTION, "____isindst_"));
anal.set_label (Label (0x10e3dd, Label::FUNCTION, "__time_less_"));
anal.set_label (Label (0x10e40d, Label::FUNCTION, "____brktime_"));
anal.set_label (Label (0x10e522, Label::FUNCTION, "___gmtime_"));
anal.set_label (Label (0x10e540, Label::FUNCTION, "_gmtime"));
anal.set_label (Label (0x10e54d, Label::FUNCTION, "____CacheOSTZ_"));
anal.set_label (Label (0x10e5a1, Label::FUNCTION, "__tryOSTimeZone_"));
anal.set_label (Label (0x10e5b9, Label::FUNCTION, "_tzset"));
anal.set_label (Label (0x10e5c7, Label::FUNCTION, "____parse_tz_"));
anal.set_label (Label (0x10e5fe, Label::FUNCTION, "__parse_time_"));
anal.set_label (Label (0x10e622, Label::FUNCTION, "__parse_offset_"));
anal.set_label (Label (0x10e74b, Label::FUNCTION, "__parse_rule_"));
anal.set_label (Label (0x10ee7c, Label::FUNCTION, "__mem_putc__0"));
anal.set_label (Label (0x10ee8f, Label::FUNCTION, "_vsprintf"));
anal.set_label (Label (0x10eea4, Label::FUNCTION, "_chdir"));
anal.set_label (Label (0x10eec5, Label::FUNCTION, "_mkdir"));
anal.set_label (Label (0x10eee6, Label::FUNCTION, "_stat"));
anal.set_label (Label (0x10f071, Label::FUNCTION, "__at2mode_"));
anal.set_label (Label (0x10f0e1, Label::FUNCTION, "_rmdir"));
anal.set_label (Label (0x10f150, Label::FUNCTION, "__nullsub_12"));
anal.set_label (Label (0x10f210, Label::FUNCTION, "__unknown_libname_1"));
anal.set_label (Label (0x10f220, Label::FUNCTION, "__unknown_libname_2"));
anal.set_label (Label (0x110663, Label::FUNCTION, "_flushall"));
anal.set_label (Label (0x110668, Label::FUNCTION, "____flushall_"));
anal.set_label (Label (0x110697, Label::FUNCTION, "_setbuf"));
anal.set_label (Label (0x112307, Label::FUNCTION, "___localtime_"));
anal.set_label (Label (0x112358, Label::FUNCTION, "_localtime"));
anal.set_label (Label (0x112365, Label::FUNCTION, "__convDec_"));
anal.set_label (Label (0x112398, Label::FUNCTION, "___asctime_"));
anal.set_label (Label (0x112485, Label::FUNCTION, "___ctime_"));
anal.set_label (Label (0x11249e, Label::FUNCTION, "_ctime"));
anal.set_label (Label (0x1124a3, Label::FUNCTION, "_asctime"));
anal.set_label (Label (0x118544, Label::FUNCTION, "____InitFiles_"));
anal.set_label (Label (0x1185bb, Label::FUNCTION, "____full_io_exit_"));
anal.set_label (Label (0x1185c7, Label::FUNCTION, "_fcloseall"));
anal.set_label (Label (0x1185cc, Label::FUNCTION, "_docloseall"));
anal.set_label (Label (0x118624, Label::FUNCTION, "____qwrite_"));
anal.set_label (Label (0x118698, Label::FUNCTION, "_intdos"));
anal.set_label (Label (0x1186e6, Label::FUNCTION, "__file_putc_"));
anal.set_label (Label (0x1186f7, Label::FUNCTION, "____fprtf_"));
anal.set_label (Label (0x118776, Label::FUNCTION, "____FDFS"));
anal.set_label (Label (0x1187c2, Label::FUNCTION, "__unknown_libname_3"));
anal.set_label (Label (0x1187d2, Label::FUNCTION, "_sbrk"));
anal.set_label (Label (0x11889a, Label::FUNCTION, "____brk_"));
anal.set_label (Label (0x118965, Label::FUNCTION, "____exit_with_msg_"));
anal.set_label (Label (0x11896a, Label::FUNCTION, "____fatal_runtime_error_"));
anal.set_label (Label (0x118987, Label::FUNCTION, "_strncpy"));
anal.set_label (Label (0x1189ac, Label::FUNCTION, "_getche"));
anal.set_label (Label (0x1189c9, Label::FUNCTION, "____delay_init_"));
anal.set_label (Label (0x1189fb, Label::FUNCTION, "____delay_"));
anal.set_label (Label (0x11b251, Label::FUNCTION, "_getch"));
anal.set_label (Label (0x11b4bc, Label::FUNCTION, "____wcpp_2_fatal_runtime_error__"));
anal.set_label (Label (0x11b6a0, Label::FUNCTION, "____wcpp_2_destruct_internal__"));
anal.set_label (Label (0x11b6aa, Label::FUNCTION, "____wcpp_2_destruct_all__"));
anal.set_label (Label (0x11b6ac, Label::FUNCTION, "____wcpp_2_destruct__"));
anal.set_label (Label (0x11b6be, Label::FUNCTION, "____wcpp_2_destruct_after_all__"));
anal.set_label (Label (0x11b6c0, Label::FUNCTION, "____wcpp_2_destruct_after__"));
anal.set_label (Label (0x11b6d0, Label::FUNCTION, "____wcpp_2_base_register__"));
anal.set_label (Label (0x11b6e9, Label::FUNCTION, "____wcpp_2_base_deregister__"));
anal.set_label (Label (0x11b6f6, Label::FUNCTION, "____int23_handler_"));
anal.set_label (Label (0x11b78b, Label::FUNCTION, "____int_ctrl_break_handler_"));
anal.set_label (Label (0x11b803, Label::FUNCTION, "____DPMI_hosted_"));
anal.set_label (Label (0x11b897, Label::FUNCTION, "____restore_int23_"));
anal.set_label (Label (0x11ba48, Label::FUNCTION, "____restore_int_"));
anal.set_label (Label (0x11ba4d, Label::FUNCTION, "____restore_int_ctrl_break_"));
anal.set_label (Label (0x11ba85, Label::FUNCTION, "____grab_int23_"));
anal.set_label (Label (0x11bba0, Label::FUNCTION, "____grab_int_ctrl_break_"));
anal.set_label (Label (0x11bcbb, Label::FUNCTION, "__j___fprtf_"));
anal.set_label (Label (0x11bcc0, Label::FUNCTION, "_strpbrk"));
anal.set_label (Label (0x11bd0a, Label::FUNCTION, "_fstat"));
anal.set_label (Label (0x11be2c, Label::FUNCTION, "___d2ttime_"));
anal.set_label (Label (0x11be92, Label::FUNCTION, "_strchr"));
anal.set_label (Label (0x11bea6, Label::FUNCTION, "____setenvp_"));
anal.set_label (Label (0x11bf7a, Label::FUNCTION, "___dos_read_"));
anal.set_label (Label (0x11bfa4, Label::FUNCTION, "___dos_write_"));
anal.set_label (Label (0x11bfab, Label::FUNCTION, "_setvbuf"));
anal.set_label (Label (0x11c012, Label::FUNCTION, "_fgets"));
anal.set_label (Label (0x11f3cd, Label::FUNCTION, "____EnterWVIDEO_"));
anal.set_label (Label (0x11f748, Label::FUNCTION, "___chain_intr_"));
anal.set_label (Label (0x11f764, Label::FUNCTION, "____wcpp_2_stab_entry__"));
anal.set_label (Label (0x11f792, Label::FUNCTION, "____wcpp_2_stab_trav_init__"));
anal.set_label (Label (0x11f7b3, Label::FUNCTION, "____wcpp_2_stab_trav_comp__"));
anal.set_label (Label (0x11f7b8, Label::FUNCTION, "____wcpp_2_stab_trav_next__"));
anal.set_label (Label (0x11f83d, Label::FUNCTION, "____wcpp_2_stab_trav_move__"));
anal.set_label (Label (0x11f8e7, Label::FUNCTION, "____wcpp_2_corrupted_stack__"));
anal.set_label (Label (0x11fc23, Label::FUNCTION, "____wcpp_2_catch_done__"));
anal.set_label (Label (0x11fe7d, Label::FUNCTION, "____wcpp_2_dispatchable__"));
anal.set_label (Label (0x11fed6, Label::FUNCTION, "____wcpp_2_save_exc__"));
anal.set_label (Label (0x11ff54, Label::FUNCTION, "____wcpp_2_dispatch__"));
anal.set_label (Label (0x12004c, Label::FUNCTION, "____wcpp_2_rethrow__"));
anal.set_label (Label (0x12005c, Label::FUNCTION, "____wcpp_2_throw__"));
anal.set_label (Label (0x120066, Label::FUNCTION, "____wcpp_2_throw_zero__"));
anal.set_label (Label (0x120164, Label::FUNCTION, "____wcpp_2_dtor_array__"));
anal.set_label (Label (0x120191, Label::FUNCTION, "____sigabort_"));
anal.set_label (Label (0x12019b, Label::FUNCTION, "____sigfpe_handler_"));
anal.set_label (Label (0x1201d0, Label::FUNCTION, "_signal"));
anal.set_label (Label (0x120285, Label::FUNCTION, "_raise"));
anal.set_label (Label (0x120347, Label::FUNCTION, "____setbits_"));
anal.set_label (Label (0x120388, Label::FUNCTION, "____wcpp_2_bit_test__"));
anal.set_label (Label (0x1203b9, Label::FUNCTION, "____wcpp_2_ts_equiv__"));
anal.set_label (Label (0x120412, Label::FUNCTION, "___setjmp_"));
anal.set_label (Label (0x120447, Label::FUNCTION, "_longjmp"));
anal.set_label (Label (0x1204cc, Label::FUNCTION, "____wcpp_2_alloc_exc__"));
anal.set_label (Label (0x120607, Label::FUNCTION, "____wcpp_2_free_exc__"));
anal.set_label (Label (0x120634, Label::FUNCTION, "____wcpp_2_pop_exc__"));
anal.set_label (Label (0x120643, Label::FUNCTION, "____wcpp_2_push_exc__"));
anal.set_label (Label (0x120650, Label::FUNCTION, "__nullsub_13"));
anal.set_label (Label (0x120681, Label::FUNCTION, "____wcpp_2_arr_register__"));
anal.set_label (Label (0x1206b1, Label::FUNCTION, "_abort"));
anal.set_label (Label (0x1206b7, Label::FUNCTION, "____terminate_"));
anal.set_label (Label (0x1206c9, Label::FUNCTION, "__j___GrabFP87_"));
anal.set_label (Label (0x120774, Label::FUNCTION, "____wcpp_2_ts_size__"));
anal.set_label (Label (0x1207b5, Label::FUNCTION, "____GrabFP87_"));
anal.set_label (Label (0x120b00, Label::FUNCTION, "____Phar_hook_init_"));
anal.set_label (Label (0x120bc3, Label::FUNCTION, "____Phar_hook_fini_"));
anal.set_label (Label (0x120bf0, Label::FUNCTION, "____DOS4G_hook_init_"));
anal.set_label (Label (0x120c1d, Label::FUNCTION, "____DOS4G_hook_fini_"));
anal.set_label (Label (0x120c36, Label::FUNCTION, "____Ergo_hook_init_"));
anal.set_label (Label (0x120c74, Label::FUNCTION, "____Ergo_hook_fini_"));
anal.set_label (Label (0x120c8e, Label::FUNCTION, "____Intel_hook_init_"));
anal.set_label (Label (0x120ce5, Label::FUNCTION, "____Intel_hook_fini__0"));
anal.set_label (Label (0x120ce6, Label::FUNCTION, "____Intel_hook_fini_"));
anal.set_label (Label (0x120ce8, Label::FUNCTION, "____save_8087_"));
anal.set_label (Label (0x120ced, Label::FUNCTION, "____rest_8087_"));
anal.set_label (Label (0x120cf1, Label::FUNCTION, "____init_8087_"));
anal.set_label (Label (0x120d22, Label::FUNCTION, "___fpreset_"));
anal.set_label (Label (0x120d2c, Label::FUNCTION, "____chk8087_"));
anal.set_label (Label (0x120d76, Label::FUNCTION, "__nullsub_15"));
anal.set_label (Label (0x120d78, Label::FUNCTION, "____init_80x87"));
